### ISSUE TITLE
MM: Headereintrag "Filter" erscheint bei jedem aktiviertem Filtreintrag

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#170]
MM: Headereintrag "Filter" erscheint bei jedem aktiviertem Filtreintrag

siehe u.a. https://github.com/MetaModels/core/issues/618

![shot30](https://cloud.githubusercontent.com/assets/1045318/12074684/6a445868-b161-11e5-916a-d978895f412d.jpg)

**Comment by xantippe** [comment]
der "Fehler" liegt daran, dass für jeden Filter ein eigener Paneleintrag erzeugt wird statt die Filter zu sammeln und in "einem Block" auszugeben...

als Workaround folgende Hinweise:

* in den Angaben des Panel-Layouts: "filter;search,limit"
* eigenes CSS für das BE anlegen http://de.contaowiki.org/Stylesheet_f%C3%BCr_Backend-Theme_erg%C3%A4nzen
* in be.css:

```css
.tl_filter.tl_subpanel {
  padding-left: 5px;
}

.tl_filter.tl_subpanel strong {
  display: none;
}

.tl_filter.tl_subpanel.last strong {
  display: inline;
}
```

dann sieht die Sache so aus:

![shot78](https://cloud.githubusercontent.com/assets/1045318/12530249/fb156ba2-c1d8-11e5-92b9-531503fda973.jpg)
